SELECT COUNT(*) AS COUNT_DATE FROM DIM_Date;

SELECT COUNT(*) AS COUNT_FACILITY FROM DIM_Facility;

SELECT COUNT(*) AS COUNT_FOODPLACES FROM DIM_FoodPlaces;

SELECT COUNT(*) AS COUNT_INSPECTIONTYPE FROM DIM_InspectionType;

SELECT COUNT(*) AS COUNT_RESULT FROM DIM_Result;

SELECT COUNT(*) AS COUNT_RISK FROM DIM_Risk;

SELECT COUNT(*) AS COUNT_VIOLATION FROM DIM_Violation;

SELECT COUNT(*) AS COUNT_FOODINSPECTION FROM FACT_FoodInspection;

SELECT COUNT(*) AS COUNT_FOODINSPVIOLATION FROM FACT_FoodInspViolation;
